// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dymensionxyz/dymension/dymns/open_purchase_order.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// OpenPurchaseOrder defines a purchase order for a Dym-Name.
// After expiry date, if no one has placed a bid, this OPO will be closed, no change.
// If there is a bid, the highest bid will win.
// OPO will be moved to historical records after completed, no matter reason.
type OpenPurchaseOrder struct {
	// The name of the Dym-Name being opened to purchase.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The last effective date of this OPO, after which the Dym-Name purchase is no longer valid.
	ExpireAt int64 `protobuf:"varint,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	// The minimum price that the seller is willing to accept for the Dym-Name.
	MinPrice types.Coin `protobuf:"bytes,4,opt,name=min_price,json=minPrice,proto3" json:"min_price"`
	// The price that the seller is willing to sell the Dym-Name for, the OPO will be closed when the price is met.
	// If the sell price is zero, the OPO will be closed when the expire_at is reached and the highest bid win.
	SellPrice types.Coin `protobuf:"bytes,5,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price"`
	// The highest bid on the OPO, if any. Price must be greater than or equal to the min_price.
	HighestBid *OpenPurchaseOrderBid `protobuf:"bytes,6,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
}

func (m *OpenPurchaseOrder) Reset()         { *m = OpenPurchaseOrder{} }
func (m *OpenPurchaseOrder) String() string { return proto.CompactTextString(m) }
func (*OpenPurchaseOrder) ProtoMessage()    {}
func (*OpenPurchaseOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_15c0ef1018f9a6fe, []int{0}
}
func (m *OpenPurchaseOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OpenPurchaseOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OpenPurchaseOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OpenPurchaseOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenPurchaseOrder.Merge(m, src)
}
func (m *OpenPurchaseOrder) XXX_Size() int {
	return m.Size()
}
func (m *OpenPurchaseOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenPurchaseOrder.DiscardUnknown(m)
}

var xxx_messageInfo_OpenPurchaseOrder proto.InternalMessageInfo

func (m *OpenPurchaseOrder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OpenPurchaseOrder) GetExpireAt() int64 {
	if m != nil {
		return m.ExpireAt
	}
	return 0
}

func (m *OpenPurchaseOrder) GetMinPrice() types.Coin {
	if m != nil {
		return m.MinPrice
	}
	return types.Coin{}
}

func (m *OpenPurchaseOrder) GetSellPrice() types.Coin {
	if m != nil {
		return m.SellPrice
	}
	return types.Coin{}
}

func (m *OpenPurchaseOrder) GetHighestBid() *OpenPurchaseOrderBid {
	if m != nil {
		return m.HighestBid
	}
	return nil
}

type OpenPurchaseOrderBid struct {
	// The address of the account which placed the bid.
	Bidder string `protobuf:"bytes,1,opt,name=bidder,proto3" json:"bidder,omitempty"`
	// The price set by the bidder.
	Price types.Coin `protobuf:"bytes,2,opt,name=price,proto3" json:"price"`
}

func (m *OpenPurchaseOrderBid) Reset()         { *m = OpenPurchaseOrderBid{} }
func (m *OpenPurchaseOrderBid) String() string { return proto.CompactTextString(m) }
func (*OpenPurchaseOrderBid) ProtoMessage()    {}
func (*OpenPurchaseOrderBid) Descriptor() ([]byte, []int) {
	return fileDescriptor_15c0ef1018f9a6fe, []int{1}
}
func (m *OpenPurchaseOrderBid) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OpenPurchaseOrderBid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OpenPurchaseOrderBid.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OpenPurchaseOrderBid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenPurchaseOrderBid.Merge(m, src)
}
func (m *OpenPurchaseOrderBid) XXX_Size() int {
	return m.Size()
}
func (m *OpenPurchaseOrderBid) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenPurchaseOrderBid.DiscardUnknown(m)
}

var xxx_messageInfo_OpenPurchaseOrderBid proto.InternalMessageInfo

func (m *OpenPurchaseOrderBid) GetBidder() string {
	if m != nil {
		return m.Bidder
	}
	return ""
}

func (m *OpenPurchaseOrderBid) GetPrice() types.Coin {
	if m != nil {
		return m.Price
	}
	return types.Coin{}
}

type HistoricalOpenPurchaseOrders struct {
	// List of closed OPOs of the same Dym-Name.
	OpenPurchaseOrders []OpenPurchaseOrder `protobuf:"bytes,1,rep,name=open_purchase_orders,json=openPurchaseOrders,proto3" json:"open_purchase_orders"`
}

func (m *HistoricalOpenPurchaseOrders) Reset()         { *m = HistoricalOpenPurchaseOrders{} }
func (m *HistoricalOpenPurchaseOrders) String() string { return proto.CompactTextString(m) }
func (*HistoricalOpenPurchaseOrders) ProtoMessage()    {}
func (*HistoricalOpenPurchaseOrders) Descriptor() ([]byte, []int) {
	return fileDescriptor_15c0ef1018f9a6fe, []int{2}
}
func (m *HistoricalOpenPurchaseOrders) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HistoricalOpenPurchaseOrders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HistoricalOpenPurchaseOrders.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HistoricalOpenPurchaseOrders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoricalOpenPurchaseOrders.Merge(m, src)
}
func (m *HistoricalOpenPurchaseOrders) XXX_Size() int {
	return m.Size()
}
func (m *HistoricalOpenPurchaseOrders) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoricalOpenPurchaseOrders.DiscardUnknown(m)
}

var xxx_messageInfo_HistoricalOpenPurchaseOrders proto.InternalMessageInfo

func (m *HistoricalOpenPurchaseOrders) GetOpenPurchaseOrders() []OpenPurchaseOrder {
	if m != nil {
		return m.OpenPurchaseOrders
	}
	return nil
}

func init() {
	proto.RegisterType((*OpenPurchaseOrder)(nil), "dymensionxyz.dymension.dymns.OpenPurchaseOrder")
	proto.RegisterType((*OpenPurchaseOrderBid)(nil), "dymensionxyz.dymension.dymns.OpenPurchaseOrderBid")
	proto.RegisterType((*HistoricalOpenPurchaseOrders)(nil), "dymensionxyz.dymension.dymns.HistoricalOpenPurchaseOrders")
}

func init() {
	proto.RegisterFile("dymensionxyz/dymension/dymns/open_purchase_order.proto", fileDescriptor_15c0ef1018f9a6fe)
}

var fileDescriptor_15c0ef1018f9a6fe = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xbf, 0x8b, 0xdb, 0x30,
	0x14, 0xc7, 0xad, 0x5c, 0x2e, 0x9c, 0x95, 0xa9, 0x22, 0x14, 0xf7, 0x7a, 0xb8, 0x26, 0x93, 0x27,
	0x89, 0xf3, 0xd1, 0x4e, 0xa5, 0x50, 0x77, 0xe9, 0x50, 0xb8, 0xc3, 0xdd, 0xba, 0x18, 0xff, 0x78,
	0xd8, 0x82, 0x58, 0x32, 0x92, 0x2e, 0x24, 0xfd, 0x07, 0xba, 0x76, 0xeb, 0xbf, 0x94, 0x31, 0x63,
	0xa7, 0x52, 0x92, 0x7f, 0xa4, 0xd8, 0x32, 0xa1, 0x90, 0xb4, 0xe4, 0xb6, 0xf7, 0xec, 0xf7, 0xd1,
	0x47, 0x7a, 0x7c, 0xf1, 0x9b, 0x72, 0xdd, 0x80, 0xd0, 0x5c, 0x8a, 0xd5, 0xfa, 0x2b, 0x3b, 0x34,
	0x5d, 0x25, 0x34, 0x93, 0x2d, 0x88, 0xb4, 0x7d, 0x54, 0x45, 0x9d, 0x69, 0x48, 0xa5, 0x2a, 0x41,
	0xd1, 0x56, 0x49, 0x23, 0xc9, 0xcd, 0xdf, 0x1c, 0x3d, 0x34, 0xb4, 0xe7, 0xae, 0x67, 0x95, 0xac,
	0x64, 0x3f, 0xc8, 0xba, 0xca, 0x32, 0xd7, 0x7e, 0x21, 0x75, 0x23, 0x35, 0xcb, 0x33, 0x0d, 0x6c,
	0x79, 0x9b, 0x83, 0xc9, 0x6e, 0x59, 0x21, 0xb9, 0xb0, 0xff, 0xe7, 0x3f, 0x46, 0xf8, 0xd9, 0x7d,
	0x0b, 0xe2, 0x61, 0x10, 0xde, 0x77, 0x3e, 0x42, 0xf0, 0x58, 0x64, 0x0d, 0x78, 0x28, 0x40, 0xa1,
	0x9b, 0xf4, 0x35, 0x79, 0x89, 0x5d, 0x58, 0xb5, 0x5c, 0x41, 0x9a, 0x19, 0x6f, 0x14, 0xa0, 0xf0,
	0x22, 0xb9, 0xb2, 0x1f, 0xde, 0x1b, 0xf2, 0x16, 0xbb, 0x0d, 0x17, 0x69, 0xab, 0x78, 0x01, 0xde,
	0x38, 0x40, 0xe1, 0x34, 0x7a, 0x41, 0xad, 0x9a, 0x76, 0x6a, 0x3a, 0xa8, 0xe9, 0x07, 0xc9, 0x45,
	0x3c, 0xde, 0xfc, 0x7a, 0xe5, 0x24, 0x57, 0x0d, 0x17, 0x0f, 0x1d, 0x40, 0xde, 0x61, 0xac, 0x61,
	0xb1, 0x18, 0xf0, 0xcb, 0xf3, 0x70, 0xb7, 0x43, 0x2c, 0xff, 0x19, 0x4f, 0x6b, 0x5e, 0xd5, 0xa0,
	0x4d, 0x9a, 0xf3, 0xd2, 0x9b, 0xf4, 0x07, 0x44, 0xf4, 0x7f, 0xeb, 0xa2, 0x47, 0x8f, 0x8e, 0x79,
	0x99, 0xe0, 0xe1, 0x98, 0x98, 0x97, 0x73, 0xc0, 0xb3, 0x53, 0x33, 0xe4, 0x39, 0x9e, 0xe4, 0xbc,
	0x2c, 0x41, 0x0d, 0xdb, 0x19, 0x3a, 0xf2, 0x1a, 0x5f, 0xda, 0xfb, 0x8f, 0xce, 0xbb, 0xbf, 0x9d,
	0x9e, 0x7f, 0x43, 0xf8, 0xe6, 0x23, 0xd7, 0x46, 0x2a, 0x5e, 0x64, 0x8b, 0x23, 0xa3, 0x26, 0x15,
	0x9e, 0x9d, 0x88, 0x84, 0xf6, 0x50, 0x70, 0x11, 0x4e, 0x23, 0xf6, 0xd4, 0x57, 0x5a, 0x39, 0x91,
	0x47, 0xa2, 0xf8, 0xd3, 0x66, 0xe7, 0xa3, 0xed, 0xce, 0x47, 0xbf, 0x77, 0x3e, 0xfa, 0xbe, 0xf7,
	0x9d, 0xed, 0xde, 0x77, 0x7e, 0xee, 0x7d, 0xe7, 0x4b, 0x54, 0x71, 0x53, 0x3f, 0xe6, 0xb4, 0x90,
	0x0d, 0xfb, 0x47, 0x76, 0x97, 0x77, 0x6c, 0x35, 0x04, 0xd8, 0xac, 0x5b, 0xd0, 0xf9, 0xa4, 0xcf,
	0xd7, 0xdd, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x43, 0x7e, 0xd2, 0xc1, 0xed, 0x02, 0x00, 0x00,
}

func (m *OpenPurchaseOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OpenPurchaseOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OpenPurchaseOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.HighestBid != nil {
		{
			size, err := m.HighestBid.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintOpenPurchaseOrder(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	{
		size, err := m.SellPrice.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintOpenPurchaseOrder(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.MinPrice.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintOpenPurchaseOrder(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.ExpireAt != 0 {
		i = encodeVarintOpenPurchaseOrder(dAtA, i, uint64(m.ExpireAt))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintOpenPurchaseOrder(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *OpenPurchaseOrderBid) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OpenPurchaseOrderBid) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OpenPurchaseOrderBid) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Price.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintOpenPurchaseOrder(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Bidder) > 0 {
		i -= len(m.Bidder)
		copy(dAtA[i:], m.Bidder)
		i = encodeVarintOpenPurchaseOrder(dAtA, i, uint64(len(m.Bidder)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *HistoricalOpenPurchaseOrders) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HistoricalOpenPurchaseOrders) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HistoricalOpenPurchaseOrders) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OpenPurchaseOrders) > 0 {
		for iNdEx := len(m.OpenPurchaseOrders) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OpenPurchaseOrders[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintOpenPurchaseOrder(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintOpenPurchaseOrder(dAtA []byte, offset int, v uint64) int {
	offset -= sovOpenPurchaseOrder(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OpenPurchaseOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovOpenPurchaseOrder(uint64(l))
	}
	if m.ExpireAt != 0 {
		n += 1 + sovOpenPurchaseOrder(uint64(m.ExpireAt))
	}
	l = m.MinPrice.Size()
	n += 1 + l + sovOpenPurchaseOrder(uint64(l))
	l = m.SellPrice.Size()
	n += 1 + l + sovOpenPurchaseOrder(uint64(l))
	if m.HighestBid != nil {
		l = m.HighestBid.Size()
		n += 1 + l + sovOpenPurchaseOrder(uint64(l))
	}
	return n
}

func (m *OpenPurchaseOrderBid) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Bidder)
	if l > 0 {
		n += 1 + l + sovOpenPurchaseOrder(uint64(l))
	}
	l = m.Price.Size()
	n += 1 + l + sovOpenPurchaseOrder(uint64(l))
	return n
}

func (m *HistoricalOpenPurchaseOrders) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.OpenPurchaseOrders) > 0 {
		for _, e := range m.OpenPurchaseOrders {
			l = e.Size()
			n += 1 + l + sovOpenPurchaseOrder(uint64(l))
		}
	}
	return n
}

func sovOpenPurchaseOrder(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOpenPurchaseOrder(x uint64) (n int) {
	return sovOpenPurchaseOrder(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OpenPurchaseOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOpenPurchaseOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OpenPurchaseOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OpenPurchaseOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpenPurchaseOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOpenPurchaseOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOpenPurchaseOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpireAt", wireType)
			}
			m.ExpireAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpenPurchaseOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpireAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpenPurchaseOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOpenPurchaseOrder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOpenPurchaseOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpenPurchaseOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOpenPurchaseOrder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOpenPurchaseOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.SellPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HighestBid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpenPurchaseOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOpenPurchaseOrder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOpenPurchaseOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.HighestBid == nil {
				m.HighestBid = &OpenPurchaseOrderBid{}
			}
			if err := m.HighestBid.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOpenPurchaseOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOpenPurchaseOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OpenPurchaseOrderBid) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOpenPurchaseOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OpenPurchaseOrderBid: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OpenPurchaseOrderBid: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bidder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpenPurchaseOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOpenPurchaseOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthOpenPurchaseOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bidder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpenPurchaseOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOpenPurchaseOrder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOpenPurchaseOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOpenPurchaseOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOpenPurchaseOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HistoricalOpenPurchaseOrders) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOpenPurchaseOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HistoricalOpenPurchaseOrders: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HistoricalOpenPurchaseOrders: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpenPurchaseOrders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOpenPurchaseOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOpenPurchaseOrder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthOpenPurchaseOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OpenPurchaseOrders = append(m.OpenPurchaseOrders, OpenPurchaseOrder{})
			if err := m.OpenPurchaseOrders[len(m.OpenPurchaseOrders)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOpenPurchaseOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthOpenPurchaseOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOpenPurchaseOrder(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOpenPurchaseOrder
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOpenPurchaseOrder
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOpenPurchaseOrder
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOpenPurchaseOrder
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupOpenPurchaseOrder
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthOpenPurchaseOrder
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthOpenPurchaseOrder        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOpenPurchaseOrder          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupOpenPurchaseOrder = fmt.Errorf("proto: unexpected end of group")
)
