// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dymensionxyz/dymension/dymns/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	Price PriceParams `protobuf:"bytes,1,opt,name=price,proto3" json:"price" yaml:"price"`
	Alias AliasParams `protobuf:"bytes,2,opt,name=alias,proto3" json:"alias" yaml:"alias"`
	Misc  MiscParams  `protobuf:"bytes,3,opt,name=misc,proto3" json:"misc" yaml:"misc"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_6097ac65688a2490, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetPrice() PriceParams {
	if m != nil {
		return m.Price
	}
	return PriceParams{}
}

func (m *Params) GetAlias() AliasParams {
	if m != nil {
		return m.Alias
	}
	return AliasParams{}
}

func (m *Params) GetMisc() MiscParams {
	if m != nil {
		return m.Misc
	}
	return MiscParams{}
}

type PriceParams struct {
	// Price of 1 letter Dym-Name, apply to first year
	Price_1Letter github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,1,opt,name=price_1_letter,json=price1Letter,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"price_1_letter" yaml:"price_1_letter"`
	// Price of 2 letters Dym-Name, apply to first year
	Price_2Letters github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,2,opt,name=price_2_letters,json=price2Letters,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"price_2_letters" yaml:"price_2_letters"`
	// Price of 3 letters Dym-Name, apply to first year
	Price_3Letters github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=price_3_letters,json=price3Letters,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"price_3_letters" yaml:"price_3_letters"`
	// Price of 4 letters Dym-Name, apply to first year
	Price_4Letters github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,4,opt,name=price_4_letters,json=price4Letters,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"price_4_letters" yaml:"price_4_letters"`
	// Price of 5+ letters Dym-Name, apply to first year
	Price_5PlusLetters github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,5,opt,name=price_5plus_letters,json=price5plusLetters,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"price_5plus_letters" yaml:"price_5plus_letters"`
	// Price extends yearly, after first year
	PriceExtends github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,6,opt,name=price_extends,json=priceExtends,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"price_extends" yaml:"price_extends"`
	// Denom of the price setup
	PriceDenom string `protobuf:"bytes,7,opt,name=price_denom,json=priceDenom,proto3" json:"price_denom,omitempty" yaml:"price_denom"`
}

func (m *PriceParams) Reset()         { *m = PriceParams{} }
func (m *PriceParams) String() string { return proto.CompactTextString(m) }
func (*PriceParams) ProtoMessage()    {}
func (*PriceParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6097ac65688a2490, []int{1}
}
func (m *PriceParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PriceParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PriceParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PriceParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceParams.Merge(m, src)
}
func (m *PriceParams) XXX_Size() int {
	return m.Size()
}
func (m *PriceParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceParams.DiscardUnknown(m)
}

var xxx_messageInfo_PriceParams proto.InternalMessageInfo

func (m *PriceParams) GetPriceDenom() string {
	if m != nil {
		return m.PriceDenom
	}
	return ""
}

type AliasParams struct {
	ByChainId map[string]AliasesOfChainId `protobuf:"bytes,1,rep,name=by_chain_id,json=byChainId,proto3" json:"by_chain_id" yaml:"by_chain_id" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *AliasParams) Reset()         { *m = AliasParams{} }
func (m *AliasParams) String() string { return proto.CompactTextString(m) }
func (*AliasParams) ProtoMessage()    {}
func (*AliasParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6097ac65688a2490, []int{2}
}
func (m *AliasParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AliasParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AliasParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AliasParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AliasParams.Merge(m, src)
}
func (m *AliasParams) XXX_Size() int {
	return m.Size()
}
func (m *AliasParams) XXX_DiscardUnknown() {
	xxx_messageInfo_AliasParams.DiscardUnknown(m)
}

var xxx_messageInfo_AliasParams proto.InternalMessageInfo

func (m *AliasParams) GetByChainId() map[string]AliasesOfChainId {
	if m != nil {
		return m.ByChainId
	}
	return nil
}

// AliasesOfChainId defines the multiple-aliases of a chain id.
type AliasesOfChainId struct {
	Aliases []string `protobuf:"bytes,1,rep,name=aliases,proto3" json:"aliases,omitempty" yaml:"aliases"`
}

func (m *AliasesOfChainId) Reset()         { *m = AliasesOfChainId{} }
func (m *AliasesOfChainId) String() string { return proto.CompactTextString(m) }
func (*AliasesOfChainId) ProtoMessage()    {}
func (*AliasesOfChainId) Descriptor() ([]byte, []int) {
	return fileDescriptor_6097ac65688a2490, []int{3}
}
func (m *AliasesOfChainId) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AliasesOfChainId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AliasesOfChainId.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AliasesOfChainId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AliasesOfChainId.Merge(m, src)
}
func (m *AliasesOfChainId) XXX_Size() int {
	return m.Size()
}
func (m *AliasesOfChainId) XXX_DiscardUnknown() {
	xxx_messageInfo_AliasesOfChainId.DiscardUnknown(m)
}

var xxx_messageInfo_AliasesOfChainId proto.InternalMessageInfo

func (m *AliasesOfChainId) GetAliases() []string {
	if m != nil {
		return m.Aliases
	}
	return nil
}

type MiscParams struct {
	BeginEpochHookIdentifier string `protobuf:"bytes,1,opt,name=begin_epoch_hook_identifier,json=beginEpochHookIdentifier,proto3" json:"begin_epoch_hook_identifier,omitempty" yaml:"begin_epoch_hook_identifier"`
	EndEpochHookIdentifier   string `protobuf:"bytes,2,opt,name=end_epoch_hook_identifier,json=endEpochHookIdentifier,proto3" json:"end_epoch_hook_identifier,omitempty" yaml:"end_epoch_hook_identifier"`
	// Number of days that the former owner of an expired Dym-Name can renew it before completely lost.
	DaysGracePeriod int32 `protobuf:"varint,3,opt,name=days_grace_period,json=daysGracePeriod,proto3" json:"days_grace_period,omitempty" yaml:"days_grace_period"`
	// Number of days of an OPO from created to expired.
	DaysOpenPurchaseOrderDuration int32 `protobuf:"varint,4,opt,name=days_open_purchase_order_duration,json=daysOpenPurchaseOrderDuration,proto3" json:"days_open_purchase_order_duration,omitempty" yaml:"days_open_purchase_order_duration"`
	// Number of days to keep history version of closed OPO before it is deleted,
	// based on expiry date and block time.
	DaysPreservedClosedPurchaseOrder int32 `protobuf:"varint,5,opt,name=days_preserved_closed_purchase_order,json=daysPreservedClosedPurchaseOrder,proto3" json:"days_preserved_closed_purchase_order,omitempty" yaml:"days_preserved_closed_purchase_order"`
	// Number of days, if the OPO expiry date enter the range before expiry of Dym-Name, the OPO can not be placed.
	DaysProhibitSell int32 `protobuf:"varint,6,opt,name=days_prohibit_sell,json=daysProhibitSell,proto3" json:"days_prohibit_sell,omitempty" yaml:"days_prohibit_sell"`
}

func (m *MiscParams) Reset()         { *m = MiscParams{} }
func (m *MiscParams) String() string { return proto.CompactTextString(m) }
func (*MiscParams) ProtoMessage()    {}
func (*MiscParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6097ac65688a2490, []int{4}
}
func (m *MiscParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MiscParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MiscParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MiscParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MiscParams.Merge(m, src)
}
func (m *MiscParams) XXX_Size() int {
	return m.Size()
}
func (m *MiscParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MiscParams.DiscardUnknown(m)
}

var xxx_messageInfo_MiscParams proto.InternalMessageInfo

func (m *MiscParams) GetBeginEpochHookIdentifier() string {
	if m != nil {
		return m.BeginEpochHookIdentifier
	}
	return ""
}

func (m *MiscParams) GetEndEpochHookIdentifier() string {
	if m != nil {
		return m.EndEpochHookIdentifier
	}
	return ""
}

func (m *MiscParams) GetDaysGracePeriod() int32 {
	if m != nil {
		return m.DaysGracePeriod
	}
	return 0
}

func (m *MiscParams) GetDaysOpenPurchaseOrderDuration() int32 {
	if m != nil {
		return m.DaysOpenPurchaseOrderDuration
	}
	return 0
}

func (m *MiscParams) GetDaysPreservedClosedPurchaseOrder() int32 {
	if m != nil {
		return m.DaysPreservedClosedPurchaseOrder
	}
	return 0
}

func (m *MiscParams) GetDaysProhibitSell() int32 {
	if m != nil {
		return m.DaysProhibitSell
	}
	return 0
}

func init() {
	proto.RegisterType((*Params)(nil), "dymensionxyz.dymension.dymns.Params")
	proto.RegisterType((*PriceParams)(nil), "dymensionxyz.dymension.dymns.PriceParams")
	proto.RegisterType((*AliasParams)(nil), "dymensionxyz.dymension.dymns.AliasParams")
	proto.RegisterMapType((map[string]AliasesOfChainId)(nil), "dymensionxyz.dymension.dymns.AliasParams.ByChainIdEntry")
	proto.RegisterType((*AliasesOfChainId)(nil), "dymensionxyz.dymension.dymns.AliasesOfChainId")
	proto.RegisterType((*MiscParams)(nil), "dymensionxyz.dymension.dymns.MiscParams")
}

func init() {
	proto.RegisterFile("dymensionxyz/dymension/dymns/params.proto", fileDescriptor_6097ac65688a2490)
}

var fileDescriptor_6097ac65688a2490 = []byte{
	// 868 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x41, 0x4f, 0xdc, 0x46,
	0x14, 0xc7, 0x59, 0x60, 0x89, 0x98, 0x4d, 0x09, 0x99, 0x50, 0xb4, 0xd9, 0x26, 0x6b, 0x3a, 0x8a,
	0x22, 0xa2, 0xa6, 0xb6, 0xd8, 0xa5, 0x6a, 0x94, 0x53, 0xeb, 0x40, 0x03, 0x2a, 0x15, 0xdb, 0xa9,
	0x7a, 0xe9, 0xc5, 0xf2, 0xda, 0x93, 0xdd, 0xd1, 0xda, 0x33, 0x96, 0xc7, 0xbb, 0xc2, 0x55, 0xa5,
	0x9e, 0x7b, 0xeb, 0xc7, 0xca, 0x31, 0xc7, 0xaa, 0x07, 0xab, 0x82, 0x7e, 0x81, 0xfa, 0xd0, 0x73,
	0xe5, 0x37, 0x5e, 0xc7, 0x90, 0x40, 0x41, 0xca, 0x09, 0xbf, 0xf7, 0xfe, 0xef, 0xff, 0x1b, 0x8f,
	0x78, 0x6f, 0x8d, 0x9e, 0xf8, 0x69, 0xc8, 0x84, 0xe2, 0x52, 0x9c, 0xa4, 0x3f, 0x5b, 0x55, 0x50,
	0x3c, 0x09, 0x65, 0x45, 0x6e, 0xec, 0x86, 0xca, 0x8c, 0x62, 0x99, 0x48, 0xfc, 0xa0, 0x2e, 0x35,
	0xab, 0xc0, 0x04, 0x69, 0x67, 0x63, 0x24, 0x47, 0x12, 0x84, 0x56, 0xf1, 0xa4, 0x7b, 0x3a, 0x5d,
	0x4f, 0xaa, 0x50, 0x2a, 0x6b, 0xe8, 0x2a, 0x66, 0xcd, 0x76, 0x86, 0x2c, 0x71, 0x77, 0x2c, 0x4f,
	0x72, 0xa1, 0xeb, 0xe4, 0xb7, 0x45, 0xb4, 0x32, 0x00, 0x08, 0xfe, 0x11, 0x35, 0xa3, 0x98, 0x7b,
	0xac, 0xdd, 0xd8, 0x6a, 0x6c, 0xb7, 0x7a, 0x4f, 0xcc, 0xab, 0x70, 0xe6, 0xa0, 0x90, 0xea, 0x4e,
	0x7b, 0xe3, 0x75, 0x66, 0x2c, 0xe4, 0x99, 0x71, 0x3b, 0x75, 0xc3, 0xe0, 0x39, 0x01, 0x17, 0x42,
	0xb5, 0x5b, 0x61, 0xeb, 0x06, 0xdc, 0x55, 0xed, 0xc5, 0xeb, 0xd8, 0x7e, 0x5d, 0x48, 0xdf, 0x6f,
	0x0b, 0x2e, 0x84, 0x6a, 0x37, 0xfc, 0x3d, 0x5a, 0x0e, 0xb9, 0xf2, 0xda, 0x4b, 0xe0, 0xba, 0x7d,
	0xb5, 0xeb, 0x77, 0x5c, 0x79, 0xa5, 0xe9, 0xbd, 0xd2, 0xb4, 0xa5, 0x4d, 0x0b, 0x0f, 0x42, 0xc1,
	0x8a, 0xfc, 0xdb, 0x44, 0xad, 0xda, 0x6b, 0xe1, 0x10, 0xad, 0xc1, 0x2b, 0x38, 0x3b, 0x4e, 0xc0,
	0x92, 0x84, 0xc5, 0x70, 0x33, 0xab, 0xf6, 0xcb, 0xc2, 0xe2, 0xcf, 0xcc, 0x78, 0x3c, 0xe2, 0xc9,
	0x78, 0x3a, 0x34, 0x3d, 0x19, 0x5a, 0xe5, 0x35, 0xeb, 0x3f, 0x9f, 0x2b, 0x7f, 0x62, 0x25, 0x69,
	0xc4, 0x94, 0x79, 0x28, 0x92, 0x3c, 0x33, 0x3e, 0xae, 0x5d, 0x4c, 0xe5, 0x46, 0xe8, 0x6d, 0x48,
	0xec, 0x1c, 0x41, 0x88, 0x23, 0x74, 0x47, 0x0b, 0x7a, 0xa5, 0x40, 0x5f, 0xd9, 0xaa, 0x7d, 0x70,
	0x63, 0xde, 0x66, 0x9d, 0x57, 0xd9, 0x11, 0xfa, 0x11, 0x64, 0x7a, 0x1a, 0xa8, 0xde, 0x12, 0xfb,
	0x15, 0x71, 0xe9, 0x43, 0x10, 0xfb, 0x17, 0x89, 0xfd, 0x77, 0x88, 0xbb, 0x15, 0x71, 0xf9, 0x43,
	0x10, 0x77, 0x2f, 0x12, 0x77, 0xe7, 0xc4, 0x5f, 0xd0, 0x3d, 0x2d, 0xf9, 0x22, 0x0a, 0xa6, 0xaa,
	0xa2, 0x36, 0x81, 0x7a, 0x74, 0x63, 0x6a, 0xa7, 0x4e, 0x3d, 0x67, 0x49, 0xe8, 0x5d, 0xc8, 0x42,
	0x72, 0x4e, 0x9f, 0x20, 0x7d, 0x1c, 0x87, 0x9d, 0x24, 0x4c, 0xf8, 0xaa, 0xbd, 0x02, 0xdc, 0x6f,
	0x6e, 0xcc, 0xdd, 0xa8, 0x73, 0x4b, 0xb3, 0xf9, 0x3f, 0xd0, 0xbe, 0x0e, 0xf1, 0x97, 0xa8, 0xa5,
	0xeb, 0x3e, 0x13, 0x32, 0x6c, 0xdf, 0x02, 0xd4, 0x66, 0x9e, 0x19, 0xb8, 0xde, 0x0c, 0x45, 0x42,
	0x11, 0x44, 0x7b, 0x10, 0xfc, 0xd3, 0x40, 0xad, 0xda, 0xe0, 0xe1, 0x04, 0xb5, 0x86, 0xa9, 0xe3,
	0x8d, 0x5d, 0x2e, 0x1c, 0xee, 0xb7, 0x1b, 0x5b, 0x4b, 0xdb, 0xad, 0xde, 0xb3, 0x6b, 0x0f, 0xae,
	0x69, 0xa7, 0x2f, 0x8a, 0xde, 0x43, 0x7f, 0x5f, 0x24, 0x71, 0x6a, 0x77, 0xca, 0x91, 0x2b, 0x8f,
	0x51, 0xb3, 0x26, 0x74, 0x75, 0x38, 0xd7, 0x76, 0x02, 0xb4, 0x76, 0xbe, 0x11, 0xaf, 0xa3, 0xa5,
	0x09, 0x4b, 0xf5, 0xd4, 0xd1, 0xe2, 0x11, 0xef, 0xa1, 0xe6, 0xcc, 0x0d, 0xa6, 0xac, 0x5c, 0x26,
	0xe6, 0x35, 0xce, 0xc4, 0xd4, 0xf1, 0xab, 0xd2, 0x95, 0xea, 0xe6, 0xe7, 0x8b, 0xcf, 0x1a, 0xe4,
	0x2b, 0xb4, 0x7e, 0xb1, 0x8c, 0x9f, 0xa2, 0x5b, 0xae, 0xce, 0xc1, 0x3b, 0xaf, 0xda, 0x38, 0xcf,
	0x8c, 0xb5, 0xda, 0xf6, 0x61, 0x8a, 0xd0, 0xb9, 0x84, 0xfc, 0xbd, 0x8c, 0xd0, 0xdb, 0xc5, 0x82,
	0x19, 0xfa, 0x64, 0xc8, 0x46, 0x5c, 0x38, 0x2c, 0x92, 0xde, 0xd8, 0x19, 0x4b, 0x39, 0x71, 0xb8,
	0xcf, 0x44, 0xc2, 0x5f, 0xf1, 0x6a, 0x75, 0x3c, 0xce, 0x33, 0x83, 0x94, 0xd7, 0x70, 0xb9, 0x98,
	0xd0, 0x36, 0x54, 0xf7, 0x8b, 0xe2, 0x81, 0x94, 0x93, 0xc3, 0xaa, 0x84, 0x1d, 0x74, 0x9f, 0x09,
	0xff, 0x12, 0x88, 0xde, 0x17, 0x8f, 0xf2, 0xcc, 0xd8, 0xd2, 0x90, 0x4b, 0xa5, 0x84, 0x6e, 0x32,
	0xe1, 0xbf, 0x0f, 0x70, 0x80, 0xee, 0xfa, 0x6e, 0xaa, 0x9c, 0x51, 0xec, 0x7a, 0xcc, 0x89, 0x58,
	0xcc, 0xa5, 0x0f, 0x6b, 0xa1, 0x69, 0x3f, 0xc8, 0x33, 0xa3, 0xad, 0x8d, 0xdf, 0x91, 0x10, 0x7a,
	0xa7, 0xc8, 0xbd, 0x2c, 0x52, 0x03, 0xc8, 0xe0, 0x19, 0xfa, 0x14, 0x64, 0x32, 0x62, 0xc2, 0x89,
	0xa6, 0xb1, 0x37, 0x76, 0x15, 0x73, 0x64, 0xec, 0xb3, 0xd8, 0xf1, 0xa7, 0xb1, 0x9b, 0x70, 0x29,
	0x60, 0xfc, 0x9b, 0xf6, 0xd3, 0x3c, 0x33, 0xb6, 0x6b, 0xce, 0x57, 0xb5, 0x10, 0xfa, 0xb0, 0xd0,
	0x1c, 0x47, 0x4c, 0x0c, 0x4a, 0xc5, 0x71, 0x21, 0xd8, 0x2b, 0xeb, 0xf8, 0x57, 0xf4, 0x08, 0x4c,
	0xa2, 0x98, 0x29, 0x16, 0xcf, 0x98, 0xef, 0x78, 0x81, 0x54, 0xcc, 0xbf, 0x60, 0x08, 0x3b, 0xa0,
	0x69, 0x5b, 0x79, 0x66, 0x7c, 0x56, 0x43, 0xff, 0x4f, 0x17, 0xa1, 0x5b, 0x85, 0x6c, 0x30, 0x57,
	0xbd, 0x00, 0xd1, 0xb9, 0x83, 0xe0, 0x6f, 0x11, 0x2e, 0xad, 0xe4, 0x98, 0x0f, 0x79, 0xe2, 0x28,
	0x16, 0x04, 0x30, 0xfa, 0x4d, 0xfb, 0x61, 0x9e, 0x19, 0xf7, 0xcf, 0xe1, 0x6a, 0x1a, 0x42, 0xd7,
	0xb5, 0xb9, 0xce, 0xfd, 0xc0, 0x82, 0xc0, 0x3e, 0x7a, 0x7d, 0xda, 0x6d, 0xbc, 0x39, 0xed, 0x36,
	0xfe, 0x3a, 0xed, 0x36, 0x7e, 0x3f, 0xeb, 0x2e, 0xbc, 0x39, 0xeb, 0x2e, 0xfc, 0x71, 0xd6, 0x5d,
	0xf8, 0xa9, 0x57, 0xdb, 0x1e, 0x97, 0x7c, 0x45, 0xcc, 0xfa, 0xd6, 0x49, 0xf9, 0x29, 0x01, 0xdb,
	0x64, 0xb8, 0x02, 0x3f, 0xfb, 0xfd, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xbc, 0x86, 0x8a,
	0x77, 0x08, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Misc.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.Alias.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Price.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PriceParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PriceParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PriceParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PriceDenom) > 0 {
		i -= len(m.PriceDenom)
		copy(dAtA[i:], m.PriceDenom)
		i = encodeVarintParams(dAtA, i, uint64(len(m.PriceDenom)))
		i--
		dAtA[i] = 0x3a
	}
	{
		size := m.PriceExtends.Size()
		i -= size
		if _, err := m.PriceExtends.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.Price_5PlusLetters.Size()
		i -= size
		if _, err := m.Price_5PlusLetters.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.Price_4Letters.Size()
		i -= size
		if _, err := m.Price_4Letters.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.Price_3Letters.Size()
		i -= size
		if _, err := m.Price_3Letters.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.Price_2Letters.Size()
		i -= size
		if _, err := m.Price_2Letters.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.Price_1Letter.Size()
		i -= size
		if _, err := m.Price_1Letter.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *AliasParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AliasParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AliasParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ByChainId) > 0 {
		for k := range m.ByChainId {
			v := m.ByChainId[k]
			baseI := i
			{
				size, err := (&v).MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintParams(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintParams(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *AliasesOfChainId) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AliasesOfChainId) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AliasesOfChainId) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Aliases) > 0 {
		for iNdEx := len(m.Aliases) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Aliases[iNdEx])
			copy(dAtA[i:], m.Aliases[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.Aliases[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *MiscParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MiscParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MiscParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DaysProhibitSell != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DaysProhibitSell))
		i--
		dAtA[i] = 0x30
	}
	if m.DaysPreservedClosedPurchaseOrder != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DaysPreservedClosedPurchaseOrder))
		i--
		dAtA[i] = 0x28
	}
	if m.DaysOpenPurchaseOrderDuration != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DaysOpenPurchaseOrderDuration))
		i--
		dAtA[i] = 0x20
	}
	if m.DaysGracePeriod != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.DaysGracePeriod))
		i--
		dAtA[i] = 0x18
	}
	if len(m.EndEpochHookIdentifier) > 0 {
		i -= len(m.EndEpochHookIdentifier)
		copy(dAtA[i:], m.EndEpochHookIdentifier)
		i = encodeVarintParams(dAtA, i, uint64(len(m.EndEpochHookIdentifier)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.BeginEpochHookIdentifier) > 0 {
		i -= len(m.BeginEpochHookIdentifier)
		copy(dAtA[i:], m.BeginEpochHookIdentifier)
		i = encodeVarintParams(dAtA, i, uint64(len(m.BeginEpochHookIdentifier)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Price.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.Alias.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.Misc.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *PriceParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Price_1Letter.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.Price_2Letters.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.Price_3Letters.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.Price_4Letters.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.Price_5PlusLetters.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.PriceExtends.Size()
	n += 1 + l + sovParams(uint64(l))
	l = len(m.PriceDenom)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func (m *AliasParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ByChainId) > 0 {
		for k, v := range m.ByChainId {
			_ = k
			_ = v
			l = v.Size()
			mapEntrySize := 1 + len(k) + sovParams(uint64(len(k))) + 1 + l + sovParams(uint64(l))
			n += mapEntrySize + 1 + sovParams(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *AliasesOfChainId) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Aliases) > 0 {
		for _, s := range m.Aliases {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	return n
}

func (m *MiscParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BeginEpochHookIdentifier)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = len(m.EndEpochHookIdentifier)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	if m.DaysGracePeriod != 0 {
		n += 1 + sovParams(uint64(m.DaysGracePeriod))
	}
	if m.DaysOpenPurchaseOrderDuration != 0 {
		n += 1 + sovParams(uint64(m.DaysOpenPurchaseOrderDuration))
	}
	if m.DaysPreservedClosedPurchaseOrder != 0 {
		n += 1 + sovParams(uint64(m.DaysPreservedClosedPurchaseOrder))
	}
	if m.DaysProhibitSell != 0 {
		n += 1 + sovParams(uint64(m.DaysProhibitSell))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Alias", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Alias.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Misc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Misc.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PriceParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PriceParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PriceParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price_1Letter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price_1Letter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price_2Letters", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price_2Letters.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price_3Letters", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price_3Letters.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price_4Letters", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price_4Letters.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price_5PlusLetters", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price_5PlusLetters.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceExtends", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.PriceExtends.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PriceDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AliasParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AliasParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AliasParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ByChainId", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ByChainId == nil {
				m.ByChainId = make(map[string]AliasesOfChainId)
			}
			var mapkey string
			mapvalue := &AliasesOfChainId{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowParams
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowParams
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthParams
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthParams
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapmsglen int
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowParams
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapmsglen |= int(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					if mapmsglen < 0 {
						return ErrInvalidLengthParams
					}
					postmsgIndex := iNdEx + mapmsglen
					if postmsgIndex < 0 {
						return ErrInvalidLengthParams
					}
					if postmsgIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = &AliasesOfChainId{}
					if err := mapvalue.Unmarshal(dAtA[iNdEx:postmsgIndex]); err != nil {
						return err
					}
					iNdEx = postmsgIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipParams(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthParams
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ByChainId[mapkey] = *mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AliasesOfChainId) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AliasesOfChainId: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AliasesOfChainId: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Aliases", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Aliases = append(m.Aliases, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MiscParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MiscParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MiscParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BeginEpochHookIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BeginEpochHookIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndEpochHookIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EndEpochHookIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DaysGracePeriod", wireType)
			}
			m.DaysGracePeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DaysGracePeriod |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DaysOpenPurchaseOrderDuration", wireType)
			}
			m.DaysOpenPurchaseOrderDuration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DaysOpenPurchaseOrderDuration |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DaysPreservedClosedPurchaseOrder", wireType)
			}
			m.DaysPreservedClosedPurchaseOrder = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DaysPreservedClosedPurchaseOrder |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DaysProhibitSell", wireType)
			}
			m.DaysProhibitSell = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DaysProhibitSell |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
