// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dymensionxyz/dymension/dymns/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fbab881fb7aa6c, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fbab881fb7aa6c, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryDymNameRequest is the request type for the Query/DymName RPC method.
type QueryDymNameRequest struct {
	DymName string `protobuf:"bytes,1,opt,name=dym_name,json=dymName,proto3" json:"dym_name,omitempty"`
}

func (m *QueryDymNameRequest) Reset()         { *m = QueryDymNameRequest{} }
func (m *QueryDymNameRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDymNameRequest) ProtoMessage()    {}
func (*QueryDymNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fbab881fb7aa6c, []int{2}
}
func (m *QueryDymNameRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDymNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDymNameRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDymNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDymNameRequest.Merge(m, src)
}
func (m *QueryDymNameRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDymNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDymNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDymNameRequest proto.InternalMessageInfo

func (m *QueryDymNameRequest) GetDymName() string {
	if m != nil {
		return m.DymName
	}
	return ""
}

// QueryDymNameResponse is the response type for the Query/DymName RPC method.
type QueryDymNameResponse struct {
	DymName *DymName `protobuf:"bytes,1,opt,name=dym_name,json=dymName,proto3" json:"dym_name,omitempty"`
}

func (m *QueryDymNameResponse) Reset()         { *m = QueryDymNameResponse{} }
func (m *QueryDymNameResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDymNameResponse) ProtoMessage()    {}
func (*QueryDymNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fbab881fb7aa6c, []int{3}
}
func (m *QueryDymNameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDymNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDymNameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDymNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDymNameResponse.Merge(m, src)
}
func (m *QueryDymNameResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDymNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDymNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDymNameResponse proto.InternalMessageInfo

func (m *QueryDymNameResponse) GetDymName() *DymName {
	if m != nil {
		return m.DymName
	}
	return nil
}

// QueryResolveDymNameAddressesRequest is the request type for the Query/ResolveDymNameAddresses RPC method.
type QueryResolveDymNameAddressesRequest struct {
	Addresses []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
}

func (m *QueryResolveDymNameAddressesRequest) Reset()         { *m = QueryResolveDymNameAddressesRequest{} }
func (m *QueryResolveDymNameAddressesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryResolveDymNameAddressesRequest) ProtoMessage()    {}
func (*QueryResolveDymNameAddressesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fbab881fb7aa6c, []int{4}
}
func (m *QueryResolveDymNameAddressesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryResolveDymNameAddressesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryResolveDymNameAddressesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryResolveDymNameAddressesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResolveDymNameAddressesRequest.Merge(m, src)
}
func (m *QueryResolveDymNameAddressesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryResolveDymNameAddressesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResolveDymNameAddressesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResolveDymNameAddressesRequest proto.InternalMessageInfo

func (m *QueryResolveDymNameAddressesRequest) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type ResultDymNameAddress struct {
	Address         string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	ResolvedAddress string `protobuf:"bytes,2,opt,name=resolved_address,json=resolvedAddress,proto3" json:"resolved_address,omitempty"`
	Error           string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (m *ResultDymNameAddress) Reset()         { *m = ResultDymNameAddress{} }
func (m *ResultDymNameAddress) String() string { return proto.CompactTextString(m) }
func (*ResultDymNameAddress) ProtoMessage()    {}
func (*ResultDymNameAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fbab881fb7aa6c, []int{5}
}
func (m *ResultDymNameAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResultDymNameAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResultDymNameAddress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResultDymNameAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResultDymNameAddress.Merge(m, src)
}
func (m *ResultDymNameAddress) XXX_Size() int {
	return m.Size()
}
func (m *ResultDymNameAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_ResultDymNameAddress.DiscardUnknown(m)
}

var xxx_messageInfo_ResultDymNameAddress proto.InternalMessageInfo

func (m *ResultDymNameAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ResultDymNameAddress) GetResolvedAddress() string {
	if m != nil {
		return m.ResolvedAddress
	}
	return ""
}

func (m *ResultDymNameAddress) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

// QueryResolveDymNameAddressesResponse is the response type for the Query/ResolveDymNameAddresses RPC method.
type QueryResolveDymNameAddressesResponse struct {
	ResolvedAddresses []ResultDymNameAddress `protobuf:"bytes,1,rep,name=resolved_addresses,json=resolvedAddresses,proto3" json:"resolved_addresses"`
}

func (m *QueryResolveDymNameAddressesResponse) Reset()         { *m = QueryResolveDymNameAddressesResponse{} }
func (m *QueryResolveDymNameAddressesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryResolveDymNameAddressesResponse) ProtoMessage()    {}
func (*QueryResolveDymNameAddressesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fbab881fb7aa6c, []int{6}
}
func (m *QueryResolveDymNameAddressesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryResolveDymNameAddressesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryResolveDymNameAddressesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryResolveDymNameAddressesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryResolveDymNameAddressesResponse.Merge(m, src)
}
func (m *QueryResolveDymNameAddressesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryResolveDymNameAddressesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryResolveDymNameAddressesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryResolveDymNameAddressesResponse proto.InternalMessageInfo

func (m *QueryResolveDymNameAddressesResponse) GetResolvedAddresses() []ResultDymNameAddress {
	if m != nil {
		return m.ResolvedAddresses
	}
	return nil
}

// QueryDymNamesOwnedByAccountRequest is the request type for the Query/DymNamesOwnedByAccount RPC method.
type QueryDymNamesOwnedByAccountRequest struct {
	// owner defines the address of the owner of the Dym-Names to query for.
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *QueryDymNamesOwnedByAccountRequest) Reset()         { *m = QueryDymNamesOwnedByAccountRequest{} }
func (m *QueryDymNamesOwnedByAccountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDymNamesOwnedByAccountRequest) ProtoMessage()    {}
func (*QueryDymNamesOwnedByAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fbab881fb7aa6c, []int{7}
}
func (m *QueryDymNamesOwnedByAccountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDymNamesOwnedByAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDymNamesOwnedByAccountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDymNamesOwnedByAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDymNamesOwnedByAccountRequest.Merge(m, src)
}
func (m *QueryDymNamesOwnedByAccountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDymNamesOwnedByAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDymNamesOwnedByAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDymNamesOwnedByAccountRequest proto.InternalMessageInfo

func (m *QueryDymNamesOwnedByAccountRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

// QueryDymNamesOwnedByAccountResponse is the response type for the Query/DymNamesOwnedByAccount RPC method.
type QueryDymNamesOwnedByAccountResponse struct {
	// dym_names defines the Dym-Names owned by the account.
	DymNames []DymName `protobuf:"bytes,1,rep,name=dym_names,json=dymNames,proto3" json:"dym_names"`
}

func (m *QueryDymNamesOwnedByAccountResponse) Reset()         { *m = QueryDymNamesOwnedByAccountResponse{} }
func (m *QueryDymNamesOwnedByAccountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDymNamesOwnedByAccountResponse) ProtoMessage()    {}
func (*QueryDymNamesOwnedByAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fbab881fb7aa6c, []int{8}
}
func (m *QueryDymNamesOwnedByAccountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDymNamesOwnedByAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDymNamesOwnedByAccountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDymNamesOwnedByAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDymNamesOwnedByAccountResponse.Merge(m, src)
}
func (m *QueryDymNamesOwnedByAccountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDymNamesOwnedByAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDymNamesOwnedByAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDymNamesOwnedByAccountResponse proto.InternalMessageInfo

func (m *QueryDymNamesOwnedByAccountResponse) GetDymNames() []DymName {
	if m != nil {
		return m.DymNames
	}
	return nil
}

// QueryOpenPurchaseOrderRequest is the request type for the Query/OpenPurchaseOrder RPC method.
type QueryOpenPurchaseOrderRequest struct {
	// dym_name is the Dym-Name to query the active OPO for.
	DymName string `protobuf:"bytes,1,opt,name=dym_name,json=dymName,proto3" json:"dym_name,omitempty"`
}

func (m *QueryOpenPurchaseOrderRequest) Reset()         { *m = QueryOpenPurchaseOrderRequest{} }
func (m *QueryOpenPurchaseOrderRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOpenPurchaseOrderRequest) ProtoMessage()    {}
func (*QueryOpenPurchaseOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fbab881fb7aa6c, []int{9}
}
func (m *QueryOpenPurchaseOrderRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOpenPurchaseOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOpenPurchaseOrderRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOpenPurchaseOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOpenPurchaseOrderRequest.Merge(m, src)
}
func (m *QueryOpenPurchaseOrderRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryOpenPurchaseOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOpenPurchaseOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOpenPurchaseOrderRequest proto.InternalMessageInfo

func (m *QueryOpenPurchaseOrderRequest) GetDymName() string {
	if m != nil {
		return m.DymName
	}
	return ""
}

// QueryOpenPurchaseOrderResponse is the response type for the Query/OpenPurchaseOrder RPC method.
type QueryOpenPurchaseOrderResponse struct {
	// result is the active OPO for the Dym-Name.
	Result OpenPurchaseOrder `protobuf:"bytes,1,opt,name=result,proto3" json:"result"`
}

func (m *QueryOpenPurchaseOrderResponse) Reset()         { *m = QueryOpenPurchaseOrderResponse{} }
func (m *QueryOpenPurchaseOrderResponse) String() string { return proto.CompactTextString(m) }
func (*QueryOpenPurchaseOrderResponse) ProtoMessage()    {}
func (*QueryOpenPurchaseOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fbab881fb7aa6c, []int{10}
}
func (m *QueryOpenPurchaseOrderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOpenPurchaseOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOpenPurchaseOrderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOpenPurchaseOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOpenPurchaseOrderResponse.Merge(m, src)
}
func (m *QueryOpenPurchaseOrderResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryOpenPurchaseOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOpenPurchaseOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOpenPurchaseOrderResponse proto.InternalMessageInfo

func (m *QueryOpenPurchaseOrderResponse) GetResult() OpenPurchaseOrder {
	if m != nil {
		return m.Result
	}
	return OpenPurchaseOrder{}
}

// QueryHistoricalPurchaseOrderRequest is the request type for the Query/HistoricalPurchaseOrder RPC method.
type QueryHistoricalPurchaseOrderRequest struct {
	// dym_name is the Dym-Name to query the historical OPO for.
	DymName string `protobuf:"bytes,1,opt,name=dym_name,json=dymName,proto3" json:"dym_name,omitempty"`
}

func (m *QueryHistoricalPurchaseOrderRequest) Reset()         { *m = QueryHistoricalPurchaseOrderRequest{} }
func (m *QueryHistoricalPurchaseOrderRequest) String() string { return proto.CompactTextString(m) }
func (*QueryHistoricalPurchaseOrderRequest) ProtoMessage()    {}
func (*QueryHistoricalPurchaseOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fbab881fb7aa6c, []int{11}
}
func (m *QueryHistoricalPurchaseOrderRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryHistoricalPurchaseOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryHistoricalPurchaseOrderRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryHistoricalPurchaseOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryHistoricalPurchaseOrderRequest.Merge(m, src)
}
func (m *QueryHistoricalPurchaseOrderRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryHistoricalPurchaseOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryHistoricalPurchaseOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryHistoricalPurchaseOrderRequest proto.InternalMessageInfo

func (m *QueryHistoricalPurchaseOrderRequest) GetDymName() string {
	if m != nil {
		return m.DymName
	}
	return ""
}

// QueryHistoricalPurchaseOrderResponse is the response type for the Query/HistoricalPurchaseOrder RPC method.
type QueryHistoricalPurchaseOrderResponse struct {
	// result defines the historical OPOs of the Dym-Name.
	Result []OpenPurchaseOrder `protobuf:"bytes,1,rep,name=result,proto3" json:"result"`
}

func (m *QueryHistoricalPurchaseOrderResponse) Reset()         { *m = QueryHistoricalPurchaseOrderResponse{} }
func (m *QueryHistoricalPurchaseOrderResponse) String() string { return proto.CompactTextString(m) }
func (*QueryHistoricalPurchaseOrderResponse) ProtoMessage()    {}
func (*QueryHistoricalPurchaseOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9fbab881fb7aa6c, []int{12}
}
func (m *QueryHistoricalPurchaseOrderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryHistoricalPurchaseOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryHistoricalPurchaseOrderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryHistoricalPurchaseOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryHistoricalPurchaseOrderResponse.Merge(m, src)
}
func (m *QueryHistoricalPurchaseOrderResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryHistoricalPurchaseOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryHistoricalPurchaseOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryHistoricalPurchaseOrderResponse proto.InternalMessageInfo

func (m *QueryHistoricalPurchaseOrderResponse) GetResult() []OpenPurchaseOrder {
	if m != nil {
		return m.Result
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "dymensionxyz.dymension.dymns.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "dymensionxyz.dymension.dymns.QueryParamsResponse")
	proto.RegisterType((*QueryDymNameRequest)(nil), "dymensionxyz.dymension.dymns.QueryDymNameRequest")
	proto.RegisterType((*QueryDymNameResponse)(nil), "dymensionxyz.dymension.dymns.QueryDymNameResponse")
	proto.RegisterType((*QueryResolveDymNameAddressesRequest)(nil), "dymensionxyz.dymension.dymns.QueryResolveDymNameAddressesRequest")
	proto.RegisterType((*ResultDymNameAddress)(nil), "dymensionxyz.dymension.dymns.ResultDymNameAddress")
	proto.RegisterType((*QueryResolveDymNameAddressesResponse)(nil), "dymensionxyz.dymension.dymns.QueryResolveDymNameAddressesResponse")
	proto.RegisterType((*QueryDymNamesOwnedByAccountRequest)(nil), "dymensionxyz.dymension.dymns.QueryDymNamesOwnedByAccountRequest")
	proto.RegisterType((*QueryDymNamesOwnedByAccountResponse)(nil), "dymensionxyz.dymension.dymns.QueryDymNamesOwnedByAccountResponse")
	proto.RegisterType((*QueryOpenPurchaseOrderRequest)(nil), "dymensionxyz.dymension.dymns.QueryOpenPurchaseOrderRequest")
	proto.RegisterType((*QueryOpenPurchaseOrderResponse)(nil), "dymensionxyz.dymension.dymns.QueryOpenPurchaseOrderResponse")
	proto.RegisterType((*QueryHistoricalPurchaseOrderRequest)(nil), "dymensionxyz.dymension.dymns.QueryHistoricalPurchaseOrderRequest")
	proto.RegisterType((*QueryHistoricalPurchaseOrderResponse)(nil), "dymensionxyz.dymension.dymns.QueryHistoricalPurchaseOrderResponse")
}

func init() {
	proto.RegisterFile("dymensionxyz/dymension/dymns/query.proto", fileDescriptor_c9fbab881fb7aa6c)
}

var fileDescriptor_c9fbab881fb7aa6c = []byte{
	// 781 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xcf, 0x4f, 0x13, 0x4d,
	0x18, 0xee, 0xf2, 0xa3, 0xd0, 0xe1, 0xf0, 0x7d, 0xcc, 0xd7, 0x7c, 0xd4, 0x06, 0x0b, 0x59, 0x41,
	0x21, 0xea, 0x2e, 0x2c, 0x09, 0x89, 0x4a, 0x0c, 0x6d, 0x88, 0x41, 0xa3, 0x82, 0x3d, 0xa9, 0x97,
	0x66, 0xe9, 0x4e, 0x4a, 0x93, 0xee, 0xce, 0x32, 0xb3, 0x0b, 0xac, 0x84, 0x8b, 0xff, 0x80, 0x26,
	0x1e, 0xbd, 0x78, 0xf7, 0xcf, 0xf0, 0xc2, 0x4d, 0x12, 0x35, 0xf1, 0x64, 0x0c, 0x78, 0xf0, 0xe0,
	0x1f, 0x61, 0x3a, 0xfb, 0x0e, 0x52, 0xe8, 0x8e, 0x0b, 0xdc, 0x76, 0x66, 0xde, 0xf7, 0x79, 0x9f,
	0xe7, 0x9d, 0x77, 0x9e, 0x16, 0x4d, 0x39, 0x91, 0x4b, 0x3c, 0xde, 0xa4, 0xde, 0x76, 0xf4, 0xc2,
	0x3c, 0x5a, 0xb4, 0xbf, 0x3c, 0x6e, 0x6e, 0x84, 0x84, 0x45, 0x86, 0xcf, 0x68, 0x40, 0xf1, 0xe8,
	0xf1, 0x48, 0xe3, 0x68, 0x61, 0x88, 0xc8, 0x62, 0xbe, 0x41, 0x1b, 0x54, 0x04, 0x9a, 0xed, 0xaf,
	0x38, 0xa7, 0x38, 0xda, 0xa0, 0xb4, 0xd1, 0x22, 0xa6, 0xed, 0x37, 0x4d, 0xdb, 0xf3, 0x68, 0x60,
	0x07, 0x4d, 0xea, 0x71, 0x38, 0x9d, 0x56, 0xd6, 0xf6, 0x6d, 0x66, 0xbb, 0x32, 0xf4, 0xba, 0x32,
	0xd4, 0x89, 0xdc, 0x9a, 0x67, 0xbb, 0x04, 0x82, 0xe7, 0x95, 0xc1, 0xd4, 0x27, 0x5e, 0xcd, 0x0f,
	0x59, 0x7d, 0xdd, 0xe6, 0xa4, 0x46, 0x99, 0x43, 0x58, 0x9c, 0xa7, 0xe7, 0x11, 0x7e, 0xd2, 0x16,
	0xbc, 0x2a, 0x2a, 0x57, 0xc9, 0x46, 0x48, 0x78, 0xa0, 0x3f, 0x43, 0xff, 0x75, 0xec, 0x72, 0x9f,
	0x7a, 0x9c, 0xe0, 0x0a, 0xca, 0xc6, 0x0c, 0x0b, 0xda, 0xb8, 0x36, 0x35, 0x64, 0x4d, 0x18, 0xaa,
	0xfe, 0x18, 0x71, 0x76, 0xa5, 0x6f, 0xef, 0xdb, 0x58, 0xa6, 0x0a, 0x99, 0xfa, 0x3c, 0x40, 0x2f,
	0x45, 0xee, 0x63, 0xdb, 0x25, 0x50, 0x11, 0x5f, 0x42, 0x83, 0x52, 0x91, 0x00, 0xcf, 0x55, 0x07,
	0x9c, 0x38, 0xe2, 0x76, 0xdf, 0xcf, 0x77, 0x63, 0x19, 0xfd, 0x29, 0xca, 0x77, 0xe6, 0x01, 0xa7,
	0xc5, 0x13, 0x89, 0x43, 0xd6, 0xa4, 0x9a, 0x95, 0x04, 0x90, 0xf8, 0xfa, 0x7d, 0x74, 0x45, 0x20,
	0x57, 0x09, 0xa7, 0xad, 0x4d, 0x02, 0xe7, 0x65, 0xc7, 0x61, 0x84, 0x73, 0x22, 0x7b, 0x82, 0x47,
	0x51, 0xce, 0x96, 0x7b, 0x05, 0x6d, 0xbc, 0x77, 0x2a, 0x57, 0xfd, 0xb3, 0x01, 0x24, 0x37, 0x50,
	0xbe, 0x4a, 0x78, 0xd8, 0x0a, 0x3a, 0x41, 0x70, 0x01, 0x0d, 0x40, 0xa8, 0x14, 0x07, 0x4b, 0x3c,
	0x8d, 0xfe, 0x65, 0x71, 0x5d, 0xa7, 0x26, 0x43, 0x7a, 0x44, 0xc8, 0x3f, 0x72, 0x5f, 0x82, 0xe4,
	0x51, 0x3f, 0x61, 0x8c, 0xb2, 0x42, 0xaf, 0x38, 0x8f, 0x17, 0xfa, 0x2b, 0x0d, 0x4d, 0xa8, 0xe9,
	0x43, 0xa3, 0x1a, 0x08, 0x9f, 0xac, 0x04, 0x42, 0x86, 0x2c, 0x4b, 0xdd, 0xb2, 0x6e, 0x9a, 0xe0,
	0x5a, 0x87, 0x4f, 0xb0, 0x24, 0x5c, 0x5f, 0x44, 0xfa, 0xf1, 0x9b, 0xe2, 0x2b, 0x5b, 0x1e, 0x71,
	0x2a, 0x51, 0xb9, 0x5e, 0xa7, 0xa1, 0x17, 0xc8, 0x76, 0xe6, 0x51, 0x3f, 0xdd, 0xf2, 0x08, 0x83,
	0x86, 0xc4, 0x0b, 0x68, 0x23, 0x85, 0x1b, 0x49, 0x42, 0x00, 0x45, 0xcb, 0x28, 0x27, 0xaf, 0x5e,
	0x0a, 0x49, 0x77, 0xf7, 0xc0, 0x7d, 0x10, 0x26, 0xa0, 0x4d, 0xf9, 0xb2, 0x28, 0xb8, 0xe2, 0x13,
	0x6f, 0x15, 0x9e, 0xc9, 0x4a, 0xfb, 0x95, 0xa4, 0x1e, 0x4f, 0x8a, 0x4a, 0x49, 0x08, 0xc0, 0xf6,
	0x11, 0xca, 0x32, 0xd1, 0x47, 0x18, 0x53, 0x53, 0x4d, 0xf5, 0x14, 0x90, 0x7c, 0x47, 0x31, 0x88,
	0x7e, 0x0f, 0x7a, 0xb4, 0xdc, 0xe4, 0x01, 0x65, 0xcd, 0xba, 0xdd, 0x3a, 0x1f, 0xf1, 0x10, 0xc6,
	0x27, 0x11, 0xa7, 0x0b, 0xfd, 0xde, 0x0b, 0xd3, 0xb7, 0x3e, 0xe4, 0x50, 0xbf, 0xa8, 0x8b, 0xdf,
	0x6a, 0x28, 0x1b, 0x3b, 0x05, 0x9e, 0x51, 0x63, 0x9e, 0x36, 0xaa, 0xe2, 0xec, 0x19, 0x32, 0x62,
	0x21, 0xfa, 0x8d, 0x97, 0x9f, 0x7e, 0xbc, 0xe9, 0xb9, 0x8a, 0x27, 0xcc, 0x14, 0x56, 0x8c, 0xdf,
	0x6b, 0x68, 0x00, 0xa6, 0x06, 0xa7, 0x29, 0xd6, 0x69, 0x6b, 0x45, 0xeb, 0x2c, 0x29, 0x40, 0xf0,
	0x96, 0x20, 0x38, 0x87, 0x67, 0xcd, 0x54, 0x3f, 0x00, 0xe6, 0x8e, 0xfc, 0xda, 0xc5, 0x1f, 0x35,
	0x34, 0x92, 0xe0, 0x03, 0xb8, 0x9c, 0x82, 0x8a, 0xda, 0x02, 0x8b, 0x95, 0x8b, 0x40, 0x80, 0xba,
	0x9b, 0x42, 0xdd, 0x35, 0x3c, 0xa9, 0x56, 0x07, 0xb6, 0x82, 0xbf, 0x68, 0xe8, 0xff, 0xee, 0x36,
	0x80, 0x17, 0xd3, 0xf7, 0xb6, 0xbb, 0x07, 0x15, 0xcb, 0x17, 0x40, 0x00, 0x39, 0xf3, 0x42, 0xce,
	0x0c, 0x36, 0xd4, 0x72, 0xda, 0xee, 0xe6, 0xd4, 0xd6, 0x22, 0x73, 0x47, 0xf8, 0xdc, 0x2e, 0xfe,
	0xac, 0xa1, 0xe1, 0x53, 0x6f, 0x04, 0xdf, 0x49, 0x41, 0x28, 0xc9, 0xa3, 0x8a, 0x0b, 0xe7, 0x4b,
	0x06, 0x21, 0x4b, 0x42, 0xc8, 0x5d, 0xbc, 0x60, 0x9e, 0xf5, 0x9f, 0xc4, 0xf1, 0x01, 0xfc, 0xa5,
	0xa1, 0x91, 0x04, 0x27, 0x49, 0x35, 0x80, 0x6a, 0x37, 0x4b, 0x35, 0x80, 0x7f, 0x31, 0x32, 0xfd,
	0x81, 0x10, 0xba, 0x84, 0x2b, 0x6a, 0xa1, 0xeb, 0x47, 0x30, 0xc9, 0x72, 0x2b, 0x0f, 0xf7, 0x0e,
	0x4a, 0xda, 0xfe, 0x41, 0x49, 0xfb, 0x7e, 0x50, 0xd2, 0x5e, 0x1f, 0x96, 0x32, 0xfb, 0x87, 0xa5,
	0xcc, 0xd7, 0xc3, 0x52, 0xe6, 0xb9, 0xd5, 0x68, 0x06, 0xeb, 0xe1, 0x9a, 0x51, 0xa7, 0x6e, 0x52,
	0x9d, 0xcd, 0x39, 0x73, 0x1b, 0x8a, 0x05, 0x91, 0x4f, 0xf8, 0x5a, 0x56, 0xfc, 0x25, 0x9b, 0xfb,
	0x1d, 0x00, 0x00, 0xff, 0xff, 0x36, 0x80, 0x4a, 0x54, 0xa0, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// DymName queries a Dym-Name by its name.
	DymName(ctx context.Context, in *QueryDymNameRequest, opts ...grpc.CallOption) (*QueryDymNameResponse, error)
	// ResolveDymNameAddresses resolves multiple Dym-Name Addresses to account addresses.
	ResolveDymNameAddresses(ctx context.Context, in *QueryResolveDymNameAddressesRequest, opts ...grpc.CallOption) (*QueryResolveDymNameAddressesResponse, error)
	// DymNamesOwnedByAccount queries the Dym-Names owned by an account.
	DymNamesOwnedByAccount(ctx context.Context, in *QueryDymNamesOwnedByAccountRequest, opts ...grpc.CallOption) (*QueryDymNamesOwnedByAccountResponse, error)
	// OpenPurchaseOrder queries the active OPO of a Dym-Name.
	OpenPurchaseOrder(ctx context.Context, in *QueryOpenPurchaseOrderRequest, opts ...grpc.CallOption) (*QueryOpenPurchaseOrderResponse, error)
	// HistoricalPurchaseOrder queries the historical OPOs of a Dym-Name.
	HistoricalPurchaseOrder(ctx context.Context, in *QueryHistoricalPurchaseOrderRequest, opts ...grpc.CallOption) (*QueryHistoricalPurchaseOrderResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/dymensionxyz.dymension.dymns.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DymName(ctx context.Context, in *QueryDymNameRequest, opts ...grpc.CallOption) (*QueryDymNameResponse, error) {
	out := new(QueryDymNameResponse)
	err := c.cc.Invoke(ctx, "/dymensionxyz.dymension.dymns.Query/DymName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ResolveDymNameAddresses(ctx context.Context, in *QueryResolveDymNameAddressesRequest, opts ...grpc.CallOption) (*QueryResolveDymNameAddressesResponse, error) {
	out := new(QueryResolveDymNameAddressesResponse)
	err := c.cc.Invoke(ctx, "/dymensionxyz.dymension.dymns.Query/ResolveDymNameAddresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DymNamesOwnedByAccount(ctx context.Context, in *QueryDymNamesOwnedByAccountRequest, opts ...grpc.CallOption) (*QueryDymNamesOwnedByAccountResponse, error) {
	out := new(QueryDymNamesOwnedByAccountResponse)
	err := c.cc.Invoke(ctx, "/dymensionxyz.dymension.dymns.Query/DymNamesOwnedByAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OpenPurchaseOrder(ctx context.Context, in *QueryOpenPurchaseOrderRequest, opts ...grpc.CallOption) (*QueryOpenPurchaseOrderResponse, error) {
	out := new(QueryOpenPurchaseOrderResponse)
	err := c.cc.Invoke(ctx, "/dymensionxyz.dymension.dymns.Query/OpenPurchaseOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) HistoricalPurchaseOrder(ctx context.Context, in *QueryHistoricalPurchaseOrderRequest, opts ...grpc.CallOption) (*QueryHistoricalPurchaseOrderResponse, error) {
	out := new(QueryHistoricalPurchaseOrderResponse)
	err := c.cc.Invoke(ctx, "/dymensionxyz.dymension.dymns.Query/HistoricalPurchaseOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// DymName queries a Dym-Name by its name.
	DymName(context.Context, *QueryDymNameRequest) (*QueryDymNameResponse, error)
	// ResolveDymNameAddresses resolves multiple Dym-Name Addresses to account addresses.
	ResolveDymNameAddresses(context.Context, *QueryResolveDymNameAddressesRequest) (*QueryResolveDymNameAddressesResponse, error)
	// DymNamesOwnedByAccount queries the Dym-Names owned by an account.
	DymNamesOwnedByAccount(context.Context, *QueryDymNamesOwnedByAccountRequest) (*QueryDymNamesOwnedByAccountResponse, error)
	// OpenPurchaseOrder queries the active OPO of a Dym-Name.
	OpenPurchaseOrder(context.Context, *QueryOpenPurchaseOrderRequest) (*QueryOpenPurchaseOrderResponse, error)
	// HistoricalPurchaseOrder queries the historical OPOs of a Dym-Name.
	HistoricalPurchaseOrder(context.Context, *QueryHistoricalPurchaseOrderRequest) (*QueryHistoricalPurchaseOrderResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) DymName(ctx context.Context, req *QueryDymNameRequest) (*QueryDymNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DymName not implemented")
}
func (*UnimplementedQueryServer) ResolveDymNameAddresses(ctx context.Context, req *QueryResolveDymNameAddressesRequest) (*QueryResolveDymNameAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveDymNameAddresses not implemented")
}
func (*UnimplementedQueryServer) DymNamesOwnedByAccount(ctx context.Context, req *QueryDymNamesOwnedByAccountRequest) (*QueryDymNamesOwnedByAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DymNamesOwnedByAccount not implemented")
}
func (*UnimplementedQueryServer) OpenPurchaseOrder(ctx context.Context, req *QueryOpenPurchaseOrderRequest) (*QueryOpenPurchaseOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenPurchaseOrder not implemented")
}
func (*UnimplementedQueryServer) HistoricalPurchaseOrder(ctx context.Context, req *QueryHistoricalPurchaseOrderRequest) (*QueryHistoricalPurchaseOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HistoricalPurchaseOrder not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dymensionxyz.dymension.dymns.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DymName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDymNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DymName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dymensionxyz.dymension.dymns.Query/DymName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DymName(ctx, req.(*QueryDymNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ResolveDymNameAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryResolveDymNameAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).ResolveDymNameAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dymensionxyz.dymension.dymns.Query/ResolveDymNameAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).ResolveDymNameAddresses(ctx, req.(*QueryResolveDymNameAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DymNamesOwnedByAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDymNamesOwnedByAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DymNamesOwnedByAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dymensionxyz.dymension.dymns.Query/DymNamesOwnedByAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DymNamesOwnedByAccount(ctx, req.(*QueryDymNamesOwnedByAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OpenPurchaseOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOpenPurchaseOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OpenPurchaseOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dymensionxyz.dymension.dymns.Query/OpenPurchaseOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OpenPurchaseOrder(ctx, req.(*QueryOpenPurchaseOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_HistoricalPurchaseOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryHistoricalPurchaseOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).HistoricalPurchaseOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/dymensionxyz.dymension.dymns.Query/HistoricalPurchaseOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).HistoricalPurchaseOrder(ctx, req.(*QueryHistoricalPurchaseOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "dymensionxyz.dymension.dymns.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "DymName",
			Handler:    _Query_DymName_Handler,
		},
		{
			MethodName: "ResolveDymNameAddresses",
			Handler:    _Query_ResolveDymNameAddresses_Handler,
		},
		{
			MethodName: "DymNamesOwnedByAccount",
			Handler:    _Query_DymNamesOwnedByAccount_Handler,
		},
		{
			MethodName: "OpenPurchaseOrder",
			Handler:    _Query_OpenPurchaseOrder_Handler,
		},
		{
			MethodName: "HistoricalPurchaseOrder",
			Handler:    _Query_HistoricalPurchaseOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dymensionxyz/dymension/dymns/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryDymNameRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDymNameRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDymNameRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DymName) > 0 {
		i -= len(m.DymName)
		copy(dAtA[i:], m.DymName)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DymName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDymNameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDymNameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDymNameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DymName != nil {
		{
			size, err := m.DymName.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryResolveDymNameAddressesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryResolveDymNameAddressesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryResolveDymNameAddressesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Addresses) > 0 {
		for iNdEx := len(m.Addresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Addresses[iNdEx])
			copy(dAtA[i:], m.Addresses[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Addresses[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ResultDymNameAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResultDymNameAddress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResultDymNameAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Error) > 0 {
		i -= len(m.Error)
		copy(dAtA[i:], m.Error)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Error)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ResolvedAddress) > 0 {
		i -= len(m.ResolvedAddress)
		copy(dAtA[i:], m.ResolvedAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ResolvedAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryResolveDymNameAddressesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryResolveDymNameAddressesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryResolveDymNameAddressesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ResolvedAddresses) > 0 {
		for iNdEx := len(m.ResolvedAddresses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ResolvedAddresses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryDymNamesOwnedByAccountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDymNamesOwnedByAccountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDymNamesOwnedByAccountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDymNamesOwnedByAccountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDymNamesOwnedByAccountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDymNamesOwnedByAccountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DymNames) > 0 {
		for iNdEx := len(m.DymNames) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.DymNames[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryOpenPurchaseOrderRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOpenPurchaseOrderRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOpenPurchaseOrderRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DymName) > 0 {
		i -= len(m.DymName)
		copy(dAtA[i:], m.DymName)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DymName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryOpenPurchaseOrderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOpenPurchaseOrderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOpenPurchaseOrderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Result.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryHistoricalPurchaseOrderRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryHistoricalPurchaseOrderRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryHistoricalPurchaseOrderRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.DymName) > 0 {
		i -= len(m.DymName)
		copy(dAtA[i:], m.DymName)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.DymName)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryHistoricalPurchaseOrderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryHistoricalPurchaseOrderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryHistoricalPurchaseOrderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Result) > 0 {
		for iNdEx := len(m.Result) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Result[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryDymNameRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DymName)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDymNameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.DymName != nil {
		l = m.DymName.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryResolveDymNameAddressesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Addresses) > 0 {
		for _, s := range m.Addresses {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *ResultDymNameAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.ResolvedAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.Error)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryResolveDymNameAddressesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ResolvedAddresses) > 0 {
		for _, e := range m.ResolvedAddresses {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryDymNamesOwnedByAccountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDymNamesOwnedByAccountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.DymNames) > 0 {
		for _, e := range m.DymNames {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryOpenPurchaseOrderRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DymName)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryOpenPurchaseOrderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Result.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryHistoricalPurchaseOrderRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DymName)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryHistoricalPurchaseOrderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Result) > 0 {
		for _, e := range m.Result {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDymNameRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDymNameRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDymNameRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DymName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DymName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDymNameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDymNameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDymNameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DymName", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DymName == nil {
				m.DymName = &DymName{}
			}
			if err := m.DymName.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryResolveDymNameAddressesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryResolveDymNameAddressesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryResolveDymNameAddressesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addresses = append(m.Addresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResultDymNameAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResultDymNameAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResultDymNameAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResolvedAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResolvedAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Error = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryResolveDymNameAddressesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryResolveDymNameAddressesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryResolveDymNameAddressesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ResolvedAddresses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResolvedAddresses = append(m.ResolvedAddresses, ResultDymNameAddress{})
			if err := m.ResolvedAddresses[len(m.ResolvedAddresses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDymNamesOwnedByAccountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDymNamesOwnedByAccountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDymNamesOwnedByAccountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDymNamesOwnedByAccountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDymNamesOwnedByAccountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDymNamesOwnedByAccountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DymNames", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DymNames = append(m.DymNames, DymName{})
			if err := m.DymNames[len(m.DymNames)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOpenPurchaseOrderRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOpenPurchaseOrderRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOpenPurchaseOrderRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DymName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DymName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOpenPurchaseOrderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOpenPurchaseOrderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOpenPurchaseOrderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Result.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryHistoricalPurchaseOrderRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryHistoricalPurchaseOrderRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryHistoricalPurchaseOrderRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DymName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DymName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryHistoricalPurchaseOrderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryHistoricalPurchaseOrderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryHistoricalPurchaseOrderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = append(m.Result, OpenPurchaseOrder{})
			if err := m.Result[len(m.Result)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
