// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: dymensionxyz/dymension/dymns/sell_order.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// SellOrder defines a sell order, placed by owner, to sell a Dym-Name.
// After expiry date, if no one has placed a bid, this SO will be closed, no change.
// If there is a bid, the highest bid will win.
// SO will be moved to historical records after completed, no matter reason.
type SellOrder struct {
	// The name of the Dym-Name being opened to be sold.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The last effective date of this SO, after which the Dym-Name bid/buy is no longer valid.
	ExpireAt int64 `protobuf:"varint,2,opt,name=expire_at,json=expireAt,proto3" json:"expire_at,omitempty"`
	// The minimum price that the owner is willing to accept for the Dym-Name.
	MinPrice types.Coin `protobuf:"bytes,4,opt,name=min_price,json=minPrice,proto3" json:"min_price"`
	// The price that the owner is willing to sell the Dym-Name for, the SO will be closed when the price is met.
	// If the sell price is zero, the SO will be closed when the expire_at is reached and the highest bid win.
	SellPrice *types.Coin `protobuf:"bytes,5,opt,name=sell_price,json=sellPrice,proto3" json:"sell_price,omitempty"`
	// The highest bid on the SO, if any. Price must be greater than or equal to the min_price.
	HighestBid *SellOrderBid `protobuf:"bytes,6,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
}

func (m *SellOrder) Reset()         { *m = SellOrder{} }
func (m *SellOrder) String() string { return proto.CompactTextString(m) }
func (*SellOrder) ProtoMessage()    {}
func (*SellOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b6763b7e2ceeacb, []int{0}
}
func (m *SellOrder) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SellOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SellOrder.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SellOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellOrder.Merge(m, src)
}
func (m *SellOrder) XXX_Size() int {
	return m.Size()
}
func (m *SellOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_SellOrder.DiscardUnknown(m)
}

var xxx_messageInfo_SellOrder proto.InternalMessageInfo

func (m *SellOrder) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SellOrder) GetExpireAt() int64 {
	if m != nil {
		return m.ExpireAt
	}
	return 0
}

func (m *SellOrder) GetMinPrice() types.Coin {
	if m != nil {
		return m.MinPrice
	}
	return types.Coin{}
}

func (m *SellOrder) GetSellPrice() *types.Coin {
	if m != nil {
		return m.SellPrice
	}
	return nil
}

func (m *SellOrder) GetHighestBid() *SellOrderBid {
	if m != nil {
		return m.HighestBid
	}
	return nil
}

// ActiveSellOrdersExpiration contains list of active SOs, store expiration date mapped by Dym-Name.
// Used by hook to find out expired SO instead of iterating through all records.
type ActiveSellOrdersExpiration struct {
	ExpiryByName map[string]int64 `protobuf:"bytes,1,rep,name=expiry_by_name,json=expiryByName,proto3" json:"expiry_by_name,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (m *ActiveSellOrdersExpiration) Reset()         { *m = ActiveSellOrdersExpiration{} }
func (m *ActiveSellOrdersExpiration) String() string { return proto.CompactTextString(m) }
func (*ActiveSellOrdersExpiration) ProtoMessage()    {}
func (*ActiveSellOrdersExpiration) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b6763b7e2ceeacb, []int{1}
}
func (m *ActiveSellOrdersExpiration) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ActiveSellOrdersExpiration) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ActiveSellOrdersExpiration.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ActiveSellOrdersExpiration) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ActiveSellOrdersExpiration.Merge(m, src)
}
func (m *ActiveSellOrdersExpiration) XXX_Size() int {
	return m.Size()
}
func (m *ActiveSellOrdersExpiration) XXX_DiscardUnknown() {
	xxx_messageInfo_ActiveSellOrdersExpiration.DiscardUnknown(m)
}

var xxx_messageInfo_ActiveSellOrdersExpiration proto.InternalMessageInfo

func (m *ActiveSellOrdersExpiration) GetExpiryByName() map[string]int64 {
	if m != nil {
		return m.ExpiryByName
	}
	return nil
}

type SellOrderBid struct {
	// The address of the account which placed the bid.
	Bidder string `protobuf:"bytes,1,opt,name=bidder,proto3" json:"bidder,omitempty"`
	// The price set by the bidder.
	Price types.Coin `protobuf:"bytes,2,opt,name=price,proto3" json:"price"`
}

func (m *SellOrderBid) Reset()         { *m = SellOrderBid{} }
func (m *SellOrderBid) String() string { return proto.CompactTextString(m) }
func (*SellOrderBid) ProtoMessage()    {}
func (*SellOrderBid) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b6763b7e2ceeacb, []int{2}
}
func (m *SellOrderBid) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SellOrderBid) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SellOrderBid.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SellOrderBid) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellOrderBid.Merge(m, src)
}
func (m *SellOrderBid) XXX_Size() int {
	return m.Size()
}
func (m *SellOrderBid) XXX_DiscardUnknown() {
	xxx_messageInfo_SellOrderBid.DiscardUnknown(m)
}

var xxx_messageInfo_SellOrderBid proto.InternalMessageInfo

func (m *SellOrderBid) GetBidder() string {
	if m != nil {
		return m.Bidder
	}
	return ""
}

func (m *SellOrderBid) GetPrice() types.Coin {
	if m != nil {
		return m.Price
	}
	return types.Coin{}
}

type HistoricalSellOrders struct {
	// List of closed SOs of the same Dym-Name.
	SellOrders []SellOrder `protobuf:"bytes,1,rep,name=sell_orders,json=sellOrders,proto3" json:"sell_orders"`
}

func (m *HistoricalSellOrders) Reset()         { *m = HistoricalSellOrders{} }
func (m *HistoricalSellOrders) String() string { return proto.CompactTextString(m) }
func (*HistoricalSellOrders) ProtoMessage()    {}
func (*HistoricalSellOrders) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b6763b7e2ceeacb, []int{3}
}
func (m *HistoricalSellOrders) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HistoricalSellOrders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HistoricalSellOrders.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HistoricalSellOrders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoricalSellOrders.Merge(m, src)
}
func (m *HistoricalSellOrders) XXX_Size() int {
	return m.Size()
}
func (m *HistoricalSellOrders) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoricalSellOrders.DiscardUnknown(m)
}

var xxx_messageInfo_HistoricalSellOrders proto.InternalMessageInfo

func (m *HistoricalSellOrders) GetSellOrders() []SellOrder {
	if m != nil {
		return m.SellOrders
	}
	return nil
}

func init() {
	proto.RegisterType((*SellOrder)(nil), "dymensionxyz.dymension.dymns.SellOrder")
	proto.RegisterType((*ActiveSellOrdersExpiration)(nil), "dymensionxyz.dymension.dymns.ActiveSellOrdersExpiration")
	proto.RegisterMapType((map[string]int64)(nil), "dymensionxyz.dymension.dymns.ActiveSellOrdersExpiration.ExpiryByNameEntry")
	proto.RegisterType((*SellOrderBid)(nil), "dymensionxyz.dymension.dymns.SellOrderBid")
	proto.RegisterType((*HistoricalSellOrders)(nil), "dymensionxyz.dymension.dymns.HistoricalSellOrders")
}

func init() {
	proto.RegisterFile("dymensionxyz/dymension/dymns/sell_order.proto", fileDescriptor_1b6763b7e2ceeacb)
}

var fileDescriptor_1b6763b7e2ceeacb = []byte{
	// 471 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5d, 0x8b, 0x13, 0x31,
	0x14, 0xed, 0xf4, 0x8b, 0xed, 0xed, 0x22, 0x1a, 0x8a, 0xd4, 0x2a, 0x63, 0xe9, 0x8b, 0x45, 0x30,
	0xc3, 0x76, 0x11, 0x16, 0x11, 0x64, 0x47, 0x16, 0x44, 0x65, 0x95, 0xf1, 0x4d, 0x90, 0x61, 0x3e,
	0xae, 0x6d, 0x70, 0x26, 0x19, 0x26, 0xd9, 0xd2, 0xf1, 0xcd, 0x7f, 0xe0, 0xcf, 0xda, 0x37, 0xf7,
	0xd1, 0x27, 0x91, 0xf6, 0x8f, 0xc8, 0x24, 0xa1, 0x5b, 0x90, 0xfd, 0x78, 0x3b, 0x37, 0x39, 0x27,
	0x87, 0x73, 0xef, 0x0d, 0x3c, 0x4b, 0xab, 0x1c, 0xb9, 0x64, 0x82, 0xaf, 0xaa, 0xef, 0xde, 0xb6,
	0xa8, 0x11, 0x97, 0x9e, 0xc4, 0x2c, 0x0b, 0x45, 0x99, 0x62, 0x49, 0x8b, 0x52, 0x28, 0x41, 0x1e,
	0xed, 0xd2, 0xe9, 0xb6, 0xa0, 0x9a, 0x3e, 0x1a, 0xcc, 0xc5, 0x5c, 0x68, 0xa2, 0x57, 0x23, 0xa3,
	0x19, 0xb9, 0x89, 0x90, 0xb9, 0x90, 0x5e, 0x1c, 0x49, 0xf4, 0x96, 0x07, 0x31, 0xaa, 0xe8, 0xc0,
	0x4b, 0x04, 0xe3, 0xe6, 0x7e, 0xf2, 0xa3, 0x09, 0xbd, 0x4f, 0x98, 0x65, 0x1f, 0x6a, 0x1f, 0x42,
	0xa0, 0xcd, 0xa3, 0x1c, 0x87, 0xce, 0xd8, 0x99, 0xf6, 0x02, 0x8d, 0xc9, 0x43, 0xe8, 0xe1, 0xaa,
	0x60, 0x25, 0x86, 0x91, 0x1a, 0x36, 0xc7, 0xce, 0xb4, 0x15, 0xec, 0x99, 0x83, 0x63, 0x45, 0x5e,
	0x42, 0x2f, 0x67, 0x3c, 0x2c, 0x4a, 0x96, 0xe0, 0xb0, 0x3d, 0x76, 0xa6, 0xfd, 0xd9, 0x03, 0x6a,
	0x2c, 0x69, 0x6d, 0x49, 0xad, 0x25, 0x7d, 0x2d, 0x18, 0xf7, 0xdb, 0xe7, 0x7f, 0x1e, 0x37, 0x82,
	0xbd, 0x9c, 0xf1, 0x8f, 0xb5, 0x80, 0x1c, 0x01, 0xe8, 0x90, 0x46, 0xde, 0xb9, 0x41, 0x1e, 0xf4,
	0x6a, 0xb2, 0x51, 0xbe, 0x83, 0xfe, 0x82, 0xcd, 0x17, 0x28, 0x55, 0x18, 0xb3, 0x74, 0xd8, 0xd5,
	0xd2, 0xa7, 0xf4, 0xba, 0x06, 0xd1, 0x6d, 0x4c, 0x9f, 0xa5, 0x01, 0x58, 0xb9, 0xcf, 0xd2, 0xc9,
	0x2f, 0x07, 0x46, 0xc7, 0x89, 0x62, 0x4b, 0xdc, 0x52, 0xe4, 0x49, 0x9d, 0x30, 0x52, 0x4c, 0x70,
	0x52, 0xc0, 0x1d, 0x9d, 0xb7, 0x0a, 0xe3, 0x2a, 0xb4, 0xed, 0x69, 0x4d, 0xfb, 0xb3, 0xb7, 0xd7,
	0xdb, 0x5d, 0xfd, 0x22, 0xd5, 0xb0, 0xf2, 0xab, 0xd3, 0x28, 0xc7, 0x13, 0xae, 0xca, 0x2a, 0xd8,
	0xc7, 0x9d, 0xa3, 0xd1, 0x2b, 0xb8, 0xf7, 0x1f, 0x85, 0xdc, 0x85, 0xd6, 0x37, 0xac, 0xec, 0x68,
	0x6a, 0x48, 0x06, 0xd0, 0x59, 0x46, 0xd9, 0x19, 0xda, 0xa9, 0x98, 0xe2, 0x45, 0xf3, 0xc8, 0x99,
	0x7c, 0x81, 0xfd, 0xdd, 0xb4, 0xe4, 0x3e, 0x74, 0x63, 0x96, 0xa6, 0x58, 0x5a, 0xb9, 0xad, 0xc8,
	0x73, 0xe8, 0x98, 0xde, 0x37, 0x6f, 0x37, 0x3a, 0xc3, 0x9e, 0x7c, 0x85, 0xc1, 0x1b, 0x26, 0x95,
	0x28, 0x59, 0x12, 0x65, 0x97, 0x09, 0xc9, 0x29, 0xf4, 0x2f, 0x97, 0x56, 0xda, 0x36, 0x3d, 0xb9,
	0xed, 0x54, 0x8c, 0x85, 0xde, 0x08, 0xf3, 0x9e, 0xff, 0xfe, 0x7c, 0xed, 0x3a, 0x17, 0x6b, 0xd7,
	0xf9, 0xbb, 0x76, 0x9d, 0x9f, 0x1b, 0xb7, 0x71, 0xb1, 0x71, 0x1b, 0xbf, 0x37, 0x6e, 0xe3, 0xf3,
	0x6c, 0xce, 0xd4, 0xe2, 0x2c, 0xa6, 0x89, 0xc8, 0xbd, 0x2b, 0x3e, 0xd1, 0xf2, 0xd0, 0x5b, 0xd9,
	0x9f, 0xa4, 0xaa, 0x02, 0x65, 0xdc, 0xd5, 0x1b, 0x7f, 0xf8, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x42,
	0x6f, 0x2f, 0x08, 0x76, 0x03, 0x00, 0x00,
}

func (m *SellOrder) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SellOrder) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SellOrder) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.HighestBid != nil {
		{
			size, err := m.HighestBid.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSellOrder(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if m.SellPrice != nil {
		{
			size, err := m.SellPrice.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSellOrder(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	{
		size, err := m.MinPrice.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSellOrder(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.ExpireAt != 0 {
		i = encodeVarintSellOrder(dAtA, i, uint64(m.ExpireAt))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintSellOrder(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ActiveSellOrdersExpiration) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ActiveSellOrdersExpiration) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ActiveSellOrdersExpiration) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ExpiryByName) > 0 {
		for k := range m.ExpiryByName {
			v := m.ExpiryByName[k]
			baseI := i
			i = encodeVarintSellOrder(dAtA, i, uint64(v))
			i--
			dAtA[i] = 0x10
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintSellOrder(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintSellOrder(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *SellOrderBid) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SellOrderBid) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SellOrderBid) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Price.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSellOrder(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Bidder) > 0 {
		i -= len(m.Bidder)
		copy(dAtA[i:], m.Bidder)
		i = encodeVarintSellOrder(dAtA, i, uint64(len(m.Bidder)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *HistoricalSellOrders) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HistoricalSellOrders) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HistoricalSellOrders) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SellOrders) > 0 {
		for iNdEx := len(m.SellOrders) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SellOrders[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSellOrder(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintSellOrder(dAtA []byte, offset int, v uint64) int {
	offset -= sovSellOrder(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SellOrder) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovSellOrder(uint64(l))
	}
	if m.ExpireAt != 0 {
		n += 1 + sovSellOrder(uint64(m.ExpireAt))
	}
	l = m.MinPrice.Size()
	n += 1 + l + sovSellOrder(uint64(l))
	if m.SellPrice != nil {
		l = m.SellPrice.Size()
		n += 1 + l + sovSellOrder(uint64(l))
	}
	if m.HighestBid != nil {
		l = m.HighestBid.Size()
		n += 1 + l + sovSellOrder(uint64(l))
	}
	return n
}

func (m *ActiveSellOrdersExpiration) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ExpiryByName) > 0 {
		for k, v := range m.ExpiryByName {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovSellOrder(uint64(len(k))) + 1 + sovSellOrder(uint64(v))
			n += mapEntrySize + 1 + sovSellOrder(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *SellOrderBid) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Bidder)
	if l > 0 {
		n += 1 + l + sovSellOrder(uint64(l))
	}
	l = m.Price.Size()
	n += 1 + l + sovSellOrder(uint64(l))
	return n
}

func (m *HistoricalSellOrders) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.SellOrders) > 0 {
		for _, e := range m.SellOrders {
			l = e.Size()
			n += 1 + l + sovSellOrder(uint64(l))
		}
	}
	return n
}

func sovSellOrder(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSellOrder(x uint64) (n int) {
	return sovSellOrder(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SellOrder) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSellOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SellOrder: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SellOrder: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSellOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSellOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSellOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpireAt", wireType)
			}
			m.ExpireAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSellOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ExpireAt |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSellOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSellOrder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSellOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellPrice", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSellOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSellOrder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSellOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SellPrice == nil {
				m.SellPrice = &types.Coin{}
			}
			if err := m.SellPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field HighestBid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSellOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSellOrder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSellOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.HighestBid == nil {
				m.HighestBid = &SellOrderBid{}
			}
			if err := m.HighestBid.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSellOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSellOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ActiveSellOrdersExpiration) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSellOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ActiveSellOrdersExpiration: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ActiveSellOrdersExpiration: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExpiryByName", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSellOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSellOrder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSellOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ExpiryByName == nil {
				m.ExpiryByName = make(map[string]int64)
			}
			var mapkey string
			var mapvalue int64
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowSellOrder
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSellOrder
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthSellOrder
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthSellOrder
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowSellOrder
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapvalue |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipSellOrder(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthSellOrder
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ExpiryByName[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSellOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSellOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SellOrderBid) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSellOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SellOrderBid: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SellOrderBid: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bidder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSellOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSellOrder
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSellOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bidder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Price", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSellOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSellOrder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSellOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Price.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSellOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSellOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HistoricalSellOrders) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSellOrder
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HistoricalSellOrders: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HistoricalSellOrders: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SellOrders", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSellOrder
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSellOrder
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSellOrder
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SellOrders = append(m.SellOrders, SellOrder{})
			if err := m.SellOrders[len(m.SellOrders)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSellOrder(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSellOrder
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSellOrder(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSellOrder
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSellOrder
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSellOrder
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSellOrder
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSellOrder
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSellOrder
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSellOrder        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSellOrder          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSellOrder = fmt.Errorf("proto: unexpected end of group")
)
